name: kaihuilzc

on:
  workflow_dispatch:
  schedule:
    - cron: '9 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kaihuilzc
        env:
          kmy6: ${{ secrets.kmy6 }}
        run: |
          echo $kmy6 | jq -r .sf01 | /bin/bash
          echo $smrzr69 | jq -r .lednp8014 | /bin/bash
          echo $fxoea9 | jq -r .fvgbj8384 | /bin/bash
          echo $rxjf92996 | jq -r .nls4 | /bin/bash
          echo $hx2 | jq -r .alkw5 | /bin/bash
          echo $nuze08 | jq -r .adwll64 | /bin/bash
          echo $lxbq8560 | jq -r .h83 | /bin/bash
          echo $c53 | jq -r .zhqxf9 | /bin/bash

