name: kaihuilzc

on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kaihuilzc
        env:
          vvhp05: ${{ secrets.vvhp05 }}
        run: |
          echo $vvhp05 | jq -r .chekp5289 | /bin/bash
          echo $dp99148 | jq -r .z4 | /bin/bash
          echo $rob6 | jq -r .c770 | /bin/bash
          echo $fxmp722 | jq -r .pzdjh715 | /bin/bash
          echo $kz2531 | jq -r .zisq98 | /bin/bash
          echo $mmsp99636 | jq -r .rzmkb1179 | /bin/bash
          echo $xlgz91789 | jq -r .dmdfe76473 | /bin/bash
          echo $zseef1113 | jq -r .gkv9676 | /bin/bash
          echo $eu90249 | jq -r .x86762 | /bin/bash

